name: CI Cache Demo

on:
  push:
    branches:
      - main

jobs:
  cache-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-ea0a419
        id: prime-cache-ea0a419       # <== REQUIRED so you can refer to its outputs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-ea0a419

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.prime-cache-ea0a419.outputs.cache-hit }}"
